#!/usr/bin/env bun
/**
 * Syncs skill-teamwork role markdown into src/prompts.generated.ts.
 * Single source of truth: skill-teamwork roles plus SKILL.md.
 * Usage: bun scripts/sync-prompts.ts [--check]
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const skillDir = join(root, "skill-teamwork");
const outFile = join(root, "src", "prompts.generated.ts");

const FILES: Array<{ role: string; path: string }> = [
  { role: "orchestrator", path: "roles/orchestrator.md" },
  { role: "explorer", path: "roles/coding/explorer.md" },
  { role: "worker", path: "roles/coding/worker.md" },
  { role: "critic", path: "roles/coding/critic.md" },
  { role: "challenger", path: "roles/coding/challenger.md" },
  { role: "auditor", path: "roles/coding/auditor.md" },
  { role: "prover", path: "roles/math/prover.md" },
  { role: "falsifier", path: "roles/math/falsifier.md" },
  { role: "verifier", path: "roles/math/verifier.md" },
  { role: "reviewer", path: "roles/review/reviewer.md" },
  { role: "synthesizer", path: "roles/review/synthesizer.md" },
  { role: "successAuditor", path: "roles/success-auditor.md" },
];

function tsString(value: string): string {
  return JSON.stringify(value);
}

async function build(): Promise<string> {
  const skillMd = await readFile(join(skillDir, "SKILL.md"), "utf8");
  const sentinelMd = await readFile(join(skillDir, "roles", "sentinel.md"), "utf8");
  const baseMd = await readFile(join(skillDir, "roles", "shared", "base.md"), "utf8");
  const roles: Array<{ role: string; content: string }> = [];
  for (const entry of FILES) {
    const content = await readFile(join(skillDir, entry.path), "utf8");
    roles.push({ role: entry.role, content });
  }
  const lines = [
    "// AUTO-GENERATED by scripts/sync-prompts.ts. Do not edit by hand.",
    "// Source of truth: skill-teamwork/SKILL.md + skill-teamwork/roles/**/*.md",
    "",
    `export const SKILL_MD = ${tsString(skillMd)};`,
    "",
    `export const SENTINEL_MD = ${tsString(sentinelMd)};`,
    "",
    `export const SHARED_BASE_MD = ${tsString(baseMd)};`,
    "",
    "export const ROLE_PROMPTS = {",
  ];
  for (const { role, content } of roles) {
    lines.push(`  ${role}: ${tsString(content)},`);
  }
  lines.push("} as const;", "", "export type GeneratedRoleName = keyof typeof ROLE_PROMPTS;", "");
  lines.push(`export const GENERATED_ROLE_NAMES = ${JSON.stringify(roles.map((r) => r.role))} as const;`, "");
  return lines.join("\n");
}

const check = process.argv.includes("--check");
const content = await build();
if (check) {
  let current = "";
  try {
    current = await readFile(outFile, "utf8");
  } catch {
    console.error("prompts.generated.ts missing; run bun scripts/sync-prompts.ts");
    process.exit(1);
  }
  if (current !== content) {
    console.error("prompts.generated.ts is stale; run bun scripts/sync-prompts.ts");
    process.exit(1);
  }
  console.log("[OK] prompts.generated.ts is in sync");
} else {
  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, content, "utf8");
  console.log(`[OK] wrote ${outFile}`);
}
